### ISSUE TITLE
Problem oko rotacije

### ISSUE THREAD

**Issue by marijal74** [MATF-RG19/RG8-rubikova-kocka#1]
Imam par problema sto se tice rotacije jedne  kolone kockice:

1.  ne valja mi logika rotacije jer iscrtava celu (staticnu) kocku (napravljene tokom init() poziva) istovremeno sa kockicom koja se pomera;
2. postoji problem i bez rotacije, samo pritiskom na dugme 'r' neke kockice gornjeg sloja se rotiraju (pojma nemam zasto se ovo javlja samo ovde, neka ideja je da se javlja jer je jedini sloj koji ne zavisi nekom transformacijom od drugog sloja);
3. dolazi do segmentation fault-a ako se rotira za vise od 90 stepeni;
4. ulazi u petlju samo jednom (jer iscrtava samo kockicu na poziciji cubes[0]).
Da li ovom logikom moram da napravim funkcije koje ce da iscratavaju staticne slojeve i ponistim samu inicijalizaciju cele kocke nekako?

Funkcija rotacije se nalazi u cube.c fajlu, on_keyboard() u main.c fajlu. U lib.h fajlu nacicete informacije kako su kockice smestene u niz cubes.

Hvala unapred.

**Comment by rastko-djordjevic-edu** [comment]
1. Slazem se. Trebalo bi da primenite sve transformacije pre (tokom) iscrtavanja kocke. 

2. U right rotation funkciji se iscrtava 8 kocki koje su sve translirane na isto mesto (1.5, 1.5, 1.5). Verovatno bi trebalo da budu translirane na odgovarajuce pozicije.

3. Izgleda mi kao da do seg faulta dolazi zbog loseg pristupa nizu cubes. Postoji staticka promenljiva "l" u fajlu cube.c koja sluzi za pristup nizu i koja uvek raste.

4.  Koju petlju? Detaljniji opis potreban.

**Comment by marijal74** [comment]
Hvala na brzom odgovoru. Slazem se povodom razloga za seg fault i to znam kako cu resiti. Verujem i da ste upravu sto se tice iscrtavanja kockica  right_rotation funkcijom. Sto se tice tacke 4, mislila sam na right_rotation funkciju, cini mi se da ulazi samo jednom i iscrtava samo prvu kockicu.
Neke stvari koje su jos ostale nerazjasnjene:

1. zasto dolazi do rotacije nekih belih kockica na gornjem sloju samo pozivom on_keyboard fje (tj. kada zakomentarisete deo koda koji poziva right_rotation kada kliknete na taster 'r' dolazi do ovog bug-a);
2. da li uopste dolazi do iscrtavanja kockice cubes[4]? Taj deo koda se nalazi u right_rotation funkciji pre petlje.

Hvala unapred.

**Comment by rastko-djordjevic-edu** [comment]
1. Kada zakomentarisem poziv funkcije right_rotation() u on_display-u, na klik dugmeta 'r' ne vidim nikakvu rotaciju.
2. Dolazi do iscrtavanja kockice pre petlje, ali je postavljena u koordinatnom pocetku pa se ne vidi. Ako biste dodali glTranslatef(3.5, 1.5, 1.5); pre iscrtavanja te kockice onda bi bilo ocigledno.

4. Ulazi (MAX_MINI=9) puta u petlju i potom iscrtava 8 kocki na istom mestu (sve kockice ce biti translirane u tacku (1.5, 1.5, 1.5) zbog poziva glTranslatef odmah pre petlje). 
Ako biste dodali glTranslatef(i, 1.5, 1.5); unutar petlje odmah nakon glPushMatrix(); onda bi bilo ocigledno da se zaista vise puta ulazi u petlju.
